services:
  capy_fe:
    build: ./frontend/
    ports:
      - "443:3000"
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://capy_be:5000

  capy_be:
    build: ./backend/
    ports:
      - "5000:5000"
    networks:
    - app-network

networks:
  app-network: {}